import { Inter } from 'next/font/google'
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

import './globals.css'
import "@/styles/main.scss"

import ReelBlocks from '@/store/ReelBlocksContext';
import ReelModalContext from '@/store/ReelModalContext';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Reels Shop',
  description: 'Generated by Reels shop',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div id="modal"></div>
        <ReelModalContext>
          <ReelBlocks>
            {children}
          </ReelBlocks>
        </ReelModalContext>
      </body>
    </html>
  )
}
